apiVersion: v1
kind: Service
metadata:
  name: ingress-service-devops
  labels:
    app: haproxy-ingress
spec:
  type: NodePort
  selector:
     app: haproxy-ingress
  ports:
   - targetPort: 80
     port: 80
     nodePort: 32456
     name: http
   - targetPort: 443
     port: 443
     nodePort: 32567
     name: https
   - targetPort: 1024
     port: 1024
     nodePort: 32678
     name: stat